server:
  port: 8080

spring:
  application:
    name: desafio-backend-it-arc-api
  profiles:
    active: ${ENV:dev}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: caffeine
  caffeine:
    spec: maximumSize=1000,expireAfterWrite=10m

security:
  jwt:
    uri: /**
    header: Authorization
    prefix: Bearer
    secret: secret