INSERT INTO notifications (status, city_name, notification_date)
VALUES
    ('PENDING', 'Sao Paulo', NOW() + INTERVAL '1 day'),
    ('PENDING', 'Rio de Janeiro', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Belo Horizonte', NOW() - INTERVAL '1 day'),
    ('PENDING', 'Porto Alegre', NOW() + INTERVAL '1 days'),
    ('PENDING', 'Salvador', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Curitiba', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Fortaleza', NOW() + INTERVAL '1 days'),
    ('PENDING', 'Recife', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Manaus', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Brasília', NOW() - INTERVAL '1 days'), -- Should throw error --
    ('PENDING', 'Sao Luis', NOW() + INTERVAL '1 days'),
    ('PENDING', 'Natal', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Vitoria', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Maceio', NOW() + INTERVAL '1 days'),
    ('PENDING', 'Joao Pessoa', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Goiania', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Belem', NOW() + INTERVAL '1 days'),
    ('PENDING', 'Florianopolis', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Campo Grande', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Sao Jose dos Campos', NOW() + INTERVAL '1 days'),
    ('PENDING', 'Sao Paulo', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Rio de Janeiro', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Belo Horizonte', NOW() + INTERVAL '1 days'),
    ('PENDING', 'Porto Alegre', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Salvador', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Curitiba', NOW() + INTERVAL '1 days'),
    ('PENDING', 'Fortaleza', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Recife', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Manaus', NOW() + INTERVAL '1 days'),
    ('PENDING', 'Brasilia', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Sao Luis', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Natal', NOW() + INTERVAL '1 days'),
    ('PENDING', 'Vitoria', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Maceio', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Joao Pessoa', NOW() + INTERVAL '1 days'),
    ('PENDING', 'Goiania', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Belem', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Florianopolis', NOW() + INTERVAL '1 days'),
    ('PENDING', 'Campo Grande', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Sao Jose dos Campos', NOW() - INTERVAL '1 days');

INSERT INTO users (name, city_name)
VALUES
    ('Lucas', 'Sao Paulo'),
    ('Maria', 'Rio de Janeiro'),
    ('Joao', 'Belo Horizonte'),
    ('Ana', 'Porto Alegre'),
    ('Carlos', 'Salvador'),
    ('Paula', 'Curitiba'),
    ('Pedro', 'Fortaleza'),
    ('Mariana', 'Recife'),
    ('Rafael', 'Manaus'),
    ('Fernanda', 'Brasilia'),
    ('Gabriel', 'Sao Luis'),
    ('Juliana', 'Natal'),
    ('Bruno', 'Vitoria'),
    ('Camila', 'Maceio'),
    ('Felipe', 'Joao Pessoa'),
    ('Larissa', 'Goiania'),
    ('Gustavo', 'Belem'),
    ('Isabela', 'Florianopolis'),
    ('Rodrigo', 'Campo Grande'),
    ('Aline', 'Sao Jose dos Campos');