INSERT INTO notifications (status, city_name, notification_date)
VALUES
    ('PENDING', 'São Paulo', NOW() + INTERVAL '1 day'),
    ('PENDING', 'Rio de Janeiro', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Belo Horizonte', NOW() - INTERVAL '1 day'),
    ('PENDING', 'Porto Alegre', NOW() + INTERVAL '1 days'),
    ('PENDING', 'Salvador', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Curitiba', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Fortaleza', NOW() + INTERVAL '1 days'),
    ('PENDING', 'Recife', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Manaus', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Brasília', NOW() + INTERVAL '1 days'),
    ('PENDING', 'São Luís', NOW() + INTERVAL '1 days'),
    ('PROCESSED', 'Natal', NOW() - INTERVAL '1 days'),
    ('ERROR', 'Vitória', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Maceió', NOW() + INTERVAL '1 days'),
    ('PROCESSED', 'João Pessoa', NOW() - INTERVAL '1 days'),
    ('ERROR', 'Goiânia', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Belém', NOW() + INTERVAL '1 days'),
    ('PROCESSED', 'Florianópolis', NOW() - INTERVAL '1 days'),
    ('ERROR', 'Campo Grande', NOW() - INTERVAL '1 days'),
    ('PENDING', 'São José dos Campos', NOW() + INTERVAL '1 days'),
    ('PROCESSED', 'São Paulo', NOW() - INTERVAL '1 days'),
    ('ERROR', 'Rio de Janeiro', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Belo Horizonte', NOW() + INTERVAL '1 days'),
    ('PROCESSED', 'Porto Alegre', NOW() - INTERVAL '1 days'),
    ('ERROR', 'Salvador', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Curitiba', NOW() + INTERVAL '1 days'),
    ('PROCESSED', 'Fortaleza', NOW() - INTERVAL '1 days'),
    ('ERROR', 'Recife', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Manaus', NOW() + INTERVAL '1 days'),
    ('PROCESSED', 'Brasília', NOW() - INTERVAL '1 days'),
    ('ERROR', 'São Luís', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Natal', NOW() + INTERVAL '1 days'),
    ('PROCESSED', 'Vitória', NOW() - INTERVAL '1 days'),
    ('ERROR', 'Maceió', NOW() - INTERVAL '1 days'),
    ('PENDING', 'João Pessoa', NOW() + INTERVAL '1 days'),
    ('PROCESSED', 'Goiânia', NOW() - INTERVAL '1 days'),
    ('ERROR', 'Belém', NOW() - INTERVAL '1 days'),
    ('PENDING', 'Florianópolis', NOW() + INTERVAL '1 days'),
    ('PROCESSED', 'Campo Grande', NOW() - INTERVAL '1 days'),
    ('ERROR', 'São José dos Campos', NOW() - INTERVAL '1 days');

INSERT INTO users (name, city_name)
VALUES
    ('Lucas', 'São Paulo'),
    ('Maria', 'Rio de Janeiro'),
    ('João', 'Belo Horizonte'),
    ('Ana', 'Porto Alegre'),
    ('Carlos', 'Salvador'),
    ('Paula', 'Curitiba'),
    ('Pedro', 'Fortaleza'),
    ('Mariana', 'Recife'),
    ('Rafael', 'Manaus'),
    ('Fernanda', 'Brasília'),
    ('Gabriel', 'São Luís'),
    ('Juliana', 'Natal'),
    ('Bruno', 'Vitória'),
    ('Camila', 'Maceió'),
    ('Felipe', 'João Pessoa'),
    ('Larissa', 'Goiânia'),
    ('Gustavo', 'Belém'),
    ('Isabela', 'Florianópolis'),
    ('Rodrigo', 'Campo Grande'),
    ('Aline', 'São José dos Campos');